### ISSUE TITLE
Total crash in FTB Direwolf20 1.20 modpack client/server environment - restoring of the world backup is necessary

### ISSUE THREAD

**Issue by PavelKCZ** [MikaylaFischler/cc-mek-scada#365]
**Describe the bug**
The game setup is as follows:

Single user world running on server (Raspberry Pi 4, but I think that this is not the issue) and client (PC, Win10).
One reactor, one turbine, one Induction multiblock

All components/computers/modems/monitors etc. are in place and I started to configure them, according to the video guide and wiki.

1. I configured the RTU - induction multiblock, turbine, environmental monitor - everything went smooth, no errors, after starting the RTU, everything is green and OK.
2. I configured the Supervisor and start it with startup. Server crashed immediately as soon as I tried to display the PLC page on the monitor. OK, maybe there is a problem and Reactor PLC must be setup first. So I restarted the server, server went online without any problem. I configured the Reactor PLC and started it (via startup). After that, I looked at Supervisor and PLC was visible and communicating with Supervisor. But RTU was missing on the display. So I checked the RTU (turbine etc.) and there was a message (sorry, I did not make a screenshot) on the display. Something about timeout or similar. So, I restarted the RTU with startup and server crashed immediately.
3. I tried to restart the server, but no luck. Server started, but after complete start sequence it stop immediately with some message from Profiler (?) that some task took more than 60 seconds and server must stop. This was not a crash, but a managed shutdown of the server.
4. I repeated several times, but the result was the same.
5. I restored the server state to the point before CC computers installation and configuration and everything is OK.

It seems that there is something wrong either with configuration/starting sequence of subsystems or there is some problem in lua code with maybe deadlock or some infinite loop.

**To Reproduce**
As mentioned above.

**Expected behavior**
I expected that all subsystems will go online, I can finish the configuration of the main computer and everything will work.

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Please include a text snippet from the log.txt files if possible, otherwise include a screenshot.

**Additional context**
The mod is excellent and I am looking forward to a full version without those annoying bugs. But as we all know, this is a software and bugs must be exterminated first. :)

**Comment by MikaylaFischler** [comment]
If there's a Minecraft crash, it's very likely ComputerCraft integration with other mods, and I can't fix that. There wouldn't be any exception I can catch, since that's at a different level than my code runs at. If an infinite loop occurred, ComputerCraft would kill my program after a few seconds and say that it ran too long without yielding.

Given that the RTU had exited for some reason, I suspect the following:

I've received one report of a crash due to ComputerCraft + Advanced Peripherals + Mekanism on Minecraft 1.20. I would suggest trying to use the system without an environment detector until Advanced Peripherals/Mekanism fixes this problem.

<img width="685" alt="image" src="https://github.com/MikaylaFischler/cc-mek-scada/assets/2926271/742f4d52-9661-4cc9-af55-515552689f21">

If you have logs or screenshots then we could confirm the cause.

**Comment by PavelKCZ** [comment]
YES - You are absolutely right. From my first crash log:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-11-05 20:57:21
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'mekanism.api.radiation.IRadiationManager mekanism.api.MekanismAPI.getRadiationManager()'
        at de.srendi.advancedperipherals.common.addons.mekanism.Mekanism.getRadiation(Mekanism.java:21) ~[AdvancedPeripherals-1.20.1-0.7.32b.jar%23381!/:0.7.32b] {re:classloading}
        at de.srendi.advancedperipherals.common.addons.mekanism.EnvironmentRadiationPlugin.getRadiation(EnvironmentRadiationPlugin.java:16) ~[AdvancedPeripherals-1.20.1-0.7.32b.jar%
23381!/:0.7.32b] {re:classloading}
        at dan200.computercraft.core.asm.PeripheralMethodSupplier.lambda$static$0(PeripheralMethodSupplier.java:27) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classl
oading}
        at dan200.computercraft.api.lua.TaskCallback.execute(TaskCallback.java:30) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classloading}
        at dan200.computercraft.core.computer.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:29) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classloading}
        at dan200.computercraft.core.computer.mainthread.MainThreadExecutor.execute(MainThreadExecutor.java:138) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classload
ing}
        at dan200.computercraft.core.computer.mainthread.MainThread.tick(MainThread.java:139) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classloading}
        at dan200.computercraft.shared.computer.core.ServerContext.tick(ServerContext.java:156) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classloading}
        at dan200.computercraft.shared.CommonHooks.onServerTickStart(CommonHooks.java:45) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classloading}
        at dan200.computercraft.shared.ForgeCommonHooks.onServerTick(ForgeCommonHooks.java:50) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classloading}
        at dan200.computercraft.shared.__ForgeCommonHooks_onServerTick_ServerTickEvent.invoke(.dynamic) ~[cc-tweaked-1.20.1-forge-1.108.3.jar%23419!/:1.108.3] {re:classloading,pl:ev
entbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:952) ~[forge-1.20.1-47.1.76-universal.jar%23660!/:?] {re:mixin,re:classloading,pl:mixin:
A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:812) ~[server-1.20.1-20230612.114412-srg.jar%23655!/:?] {re:mixin,pl:accesstransformer:B,re:computing_fr
ames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resource
s.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:
ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,p
l:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23655!/:?] {re:mixin,pl:accesstransformer:B,re:computing_
frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resour
ces.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:AP
P:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin
,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23655!/:?] {re:mixin,pl:accesstransformer:B,re:computing_
frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resour
ces.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:AP
P:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin
,pl:mixin:A}
        at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------


We can close this issue, problem is somewhere else. :)
